#!/usr/bin/env bash
# Script that display THe Text Best School and Hi using while and if

counter=1

while [ $counter -le 9 ]; do
	if [ $counter -eq 9 ]; then
                echo "Best School"
		echo "Hi"
	fi
	echo "Best School"
	((counter++))
done
