#!/usr/bin/env bash
#Script that print using a nested while loop

counter=0
hour="Hour:"
while [ $counter -le 12 ]; do
	echo "$hour $counter"
        minute=1
	while [ $minute -le 59 ]; do
	       echo $minute
               ((minute++))
        done
        ((counter++))
done	
